name: coffee-paste

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm i -g yarn
        yarn install --frozen-lockfile
        yarn prepare
        yarn build
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: bundle
    #     path: dist